// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: manifest_meta.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ManifestMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// meta info for what this manifest was generated from
	NarinfoUrl             string   `protobuf:"bytes,1,opt,name=narinfo_url,json=narinfoUrl,proto3" json:"narinfo_url,omitempty"`                                       // url that narinfo was fetched from
	Narinfo                *NarInfo `protobuf:"bytes,2,opt,name=narinfo,proto3" json:"narinfo,omitempty"`                                                               // parsed or generated narinfo (includes references, signatures, etc.)
	GenericTarballOriginal string   `protobuf:"bytes,3,opt,name=generic_tarball_original,json=genericTarballOriginal,proto3" json:"generic_tarball_original,omitempty"` // generic tarball origin and final url
	GenericTarballResolved string   `protobuf:"bytes,4,opt,name=generic_tarball_resolved,json=genericTarballResolved,proto3" json:"generic_tarball_resolved,omitempty"`
	Generator              string   `protobuf:"bytes,10,opt,name=generator,proto3" json:"generator,omitempty"`                               // software version of generator
	GeneratedTime          int64    `protobuf:"varint,11,opt,name=generated_time,json=generatedTime,proto3" json:"generated_time,omitempty"` // timestamp when this was generated (unix seconds)
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ManifestMeta) Reset() {
	*x = ManifestMeta{}
	mi := &file_manifest_meta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestMeta) ProtoMessage() {}

func (x *ManifestMeta) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_meta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestMeta.ProtoReflect.Descriptor instead.
func (*ManifestMeta) Descriptor() ([]byte, []int) {
	return file_manifest_meta_proto_rawDescGZIP(), []int{0}
}

func (x *ManifestMeta) GetNarinfoUrl() string {
	if x != nil {
		return x.NarinfoUrl
	}
	return ""
}

func (x *ManifestMeta) GetNarinfo() *NarInfo {
	if x != nil {
		return x.Narinfo
	}
	return nil
}

func (x *ManifestMeta) GetGenericTarballOriginal() string {
	if x != nil {
		return x.GenericTarballOriginal
	}
	return ""
}

func (x *ManifestMeta) GetGenericTarballResolved() string {
	if x != nil {
		return x.GenericTarballResolved
	}
	return ""
}

func (x *ManifestMeta) GetGenerator() string {
	if x != nil {
		return x.Generator
	}
	return ""
}

func (x *ManifestMeta) GetGeneratedTime() int64 {
	if x != nil {
		return x.GeneratedTime
	}
	return 0
}

var File_manifest_meta_proto protoreflect.FileDescriptor

const file_manifest_meta_proto_rawDesc = "" +
	"\n" +
	"\x13manifest_meta.proto\x12\x02pb\x1a\rnarinfo.proto\"\x8f\x02\n" +
	"\fManifestMeta\x12\x1f\n" +
	"\vnarinfo_url\x18\x01 \x01(\tR\n" +
	"narinfoUrl\x12%\n" +
	"\anarinfo\x18\x02 \x01(\v2\v.pb.NarInfoR\anarinfo\x128\n" +
	"\x18generic_tarball_original\x18\x03 \x01(\tR\x16genericTarballOriginal\x128\n" +
	"\x18generic_tarball_resolved\x18\x04 \x01(\tR\x16genericTarballResolved\x12\x1c\n" +
	"\tgenerator\x18\n" +
	" \x01(\tR\tgenerator\x12%\n" +
	"\x0egenerated_time\x18\v \x01(\x03R\rgeneratedTimeB\x18Z\x16github.com/dnr/styx/pbb\x06proto3"

var (
	file_manifest_meta_proto_rawDescOnce sync.Once
	file_manifest_meta_proto_rawDescData []byte
)

func file_manifest_meta_proto_rawDescGZIP() []byte {
	file_manifest_meta_proto_rawDescOnce.Do(func() {
		file_manifest_meta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_manifest_meta_proto_rawDesc), len(file_manifest_meta_proto_rawDesc)))
	})
	return file_manifest_meta_proto_rawDescData
}

var file_manifest_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_manifest_meta_proto_goTypes = []any{
	(*ManifestMeta)(nil), // 0: pb.ManifestMeta
	(*NarInfo)(nil),      // 1: pb.NarInfo
}
var file_manifest_meta_proto_depIdxs = []int32{
	1, // 0: pb.ManifestMeta.narinfo:type_name -> pb.NarInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_manifest_meta_proto_init() }
func file_manifest_meta_proto_init() {
	if File_manifest_meta_proto != nil {
		return
	}
	file_narinfo_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_manifest_meta_proto_rawDesc), len(file_manifest_meta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_manifest_meta_proto_goTypes,
		DependencyIndexes: file_manifest_meta_proto_depIdxs,
		MessageInfos:      file_manifest_meta_proto_msgTypes,
	}.Build()
	File_manifest_meta_proto = out.File
	file_manifest_meta_proto_goTypes = nil
	file_manifest_meta_proto_depIdxs = nil
}
