// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: manifester.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ManifesterChunkDiffReq struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Params *GlobalParams          `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"` // for compatibility check
	Bases  []byte                 `protobuf:"bytes,2,opt,name=bases,proto3" json:"bases,omitempty"`
	Reqs   []byte                 `protobuf:"bytes,3,opt,name=reqs,proto3" json:"reqs,omitempty"`
	// If set: Bases and Reqs each comprise one single file in the given compression
	// format. Pass each one through this decompressor before diffing.
	ExpandBeforeDiff string `protobuf:"bytes,4,opt,name=expand_before_diff,json=expandBeforeDiff,proto3" json:"expand_before_diff,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ManifesterChunkDiffReq) Reset() {
	*x = ManifesterChunkDiffReq{}
	mi := &file_manifester_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifesterChunkDiffReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifesterChunkDiffReq) ProtoMessage() {}

func (x *ManifesterChunkDiffReq) ProtoReflect() protoreflect.Message {
	mi := &file_manifester_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifesterChunkDiffReq.ProtoReflect.Descriptor instead.
func (*ManifesterChunkDiffReq) Descriptor() ([]byte, []int) {
	return file_manifester_proto_rawDescGZIP(), []int{0}
}

func (x *ManifesterChunkDiffReq) GetParams() *GlobalParams {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ManifesterChunkDiffReq) GetBases() []byte {
	if x != nil {
		return x.Bases
	}
	return nil
}

func (x *ManifesterChunkDiffReq) GetReqs() []byte {
	if x != nil {
		return x.Reqs
	}
	return nil
}

func (x *ManifesterChunkDiffReq) GetExpandBeforeDiff() string {
	if x != nil {
		return x.ExpandBeforeDiff
	}
	return ""
}

var File_manifester_proto protoreflect.FileDescriptor

const file_manifester_proto_rawDesc = "" +
	"\n" +
	"\x10manifester.proto\x12\x02pb\x1a\fparams.proto\"\x9a\x01\n" +
	"\x16ManifesterChunkDiffReq\x12(\n" +
	"\x06params\x18\x01 \x01(\v2\x10.pb.GlobalParamsR\x06params\x12\x14\n" +
	"\x05bases\x18\x02 \x01(\fR\x05bases\x12\x12\n" +
	"\x04reqs\x18\x03 \x01(\fR\x04reqs\x12,\n" +
	"\x12expand_before_diff\x18\x04 \x01(\tR\x10expandBeforeDiffB\x18Z\x16github.com/dnr/styx/pbb\x06proto3"

var (
	file_manifester_proto_rawDescOnce sync.Once
	file_manifester_proto_rawDescData []byte
)

func file_manifester_proto_rawDescGZIP() []byte {
	file_manifester_proto_rawDescOnce.Do(func() {
		file_manifester_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_manifester_proto_rawDesc), len(file_manifester_proto_rawDesc)))
	})
	return file_manifester_proto_rawDescData
}

var file_manifester_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_manifester_proto_goTypes = []any{
	(*ManifesterChunkDiffReq)(nil), // 0: pb.ManifesterChunkDiffReq
	(*GlobalParams)(nil),           // 1: pb.GlobalParams
}
var file_manifester_proto_depIdxs = []int32{
	1, // 0: pb.ManifesterChunkDiffReq.params:type_name -> pb.GlobalParams
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_manifester_proto_init() }
func file_manifester_proto_init() {
	if File_manifester_proto != nil {
		return
	}
	file_params_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_manifester_proto_rawDesc), len(file_manifester_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_manifester_proto_goTypes,
		DependencyIndexes: file_manifester_proto_depIdxs,
		MessageInfos:      file_manifester_proto_msgTypes,
	}.Build()
	File_manifester_proto = out.File
	file_manifester_proto_goTypes = nil
	file_manifester_proto_depIdxs = nil
}
