// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: narinfo.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// from github.com/nix-community/go-nix pkg/narinfo/types.go
type NarInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StorePath   string `protobuf:"bytes,1,opt,name=store_path,json=storePath,proto3" json:"store_path,omitempty"` // The full nix store path (/nix/store/…-pname-version)
	Url         string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`                              // The relative location to the .nar[.xz,…] file. Usually nar/$fileHash.nar[.xz]
	Compression string `protobuf:"bytes,3,opt,name=compression,proto3" json:"compression,omitempty"`              // The compression method file at URL is compressed with (none,xz,…)
	FileHash    string `protobuf:"bytes,4,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`    // The hash of the file at URL (nix string format)
	FileSize    int64  `protobuf:"varint,5,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`   // The size of the file at URL, in bytes
	// The hash of the .nar file, after possible decompression (nix string format)
	// Identical to FileHash if no compression is used.
	NarHash string `protobuf:"bytes,6,opt,name=nar_hash,json=narHash,proto3" json:"nar_hash,omitempty"`
	// The size of the .nar file, after possible decompression, in bytes.
	// Identical to FileSize if no compression is used.
	NarSize    int64    `protobuf:"varint,7,opt,name=nar_size,json=narSize,proto3" json:"nar_size,omitempty"`
	References []string `protobuf:"bytes,8,rep,name=references,proto3" json:"references,omitempty"`  // References to other store paths, contained in the .nar file
	Deriver    string   `protobuf:"bytes,9,opt,name=deriver,proto3" json:"deriver,omitempty"`        // Path of the .drv for this store path
	System     string   `protobuf:"bytes,10,opt,name=system,proto3" json:"system,omitempty"`         // This doesn't seem to be used at all?
	Signatures []string `protobuf:"bytes,11,rep,name=signatures,proto3" json:"signatures,omitempty"` // Signatures, if any.
	Ca         string   `protobuf:"bytes,12,opt,name=ca,proto3" json:"ca,omitempty"`
}

func (x *NarInfo) Reset() {
	*x = NarInfo{}
	mi := &file_narinfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NarInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NarInfo) ProtoMessage() {}

func (x *NarInfo) ProtoReflect() protoreflect.Message {
	mi := &file_narinfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NarInfo.ProtoReflect.Descriptor instead.
func (*NarInfo) Descriptor() ([]byte, []int) {
	return file_narinfo_proto_rawDescGZIP(), []int{0}
}

func (x *NarInfo) GetStorePath() string {
	if x != nil {
		return x.StorePath
	}
	return ""
}

func (x *NarInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *NarInfo) GetCompression() string {
	if x != nil {
		return x.Compression
	}
	return ""
}

func (x *NarInfo) GetFileHash() string {
	if x != nil {
		return x.FileHash
	}
	return ""
}

func (x *NarInfo) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *NarInfo) GetNarHash() string {
	if x != nil {
		return x.NarHash
	}
	return ""
}

func (x *NarInfo) GetNarSize() int64 {
	if x != nil {
		return x.NarSize
	}
	return 0
}

func (x *NarInfo) GetReferences() []string {
	if x != nil {
		return x.References
	}
	return nil
}

func (x *NarInfo) GetDeriver() string {
	if x != nil {
		return x.Deriver
	}
	return ""
}

func (x *NarInfo) GetSystem() string {
	if x != nil {
		return x.System
	}
	return ""
}

func (x *NarInfo) GetSignatures() []string {
	if x != nil {
		return x.Signatures
	}
	return nil
}

func (x *NarInfo) GetCa() string {
	if x != nil {
		return x.Ca
	}
	return ""
}

var File_narinfo_proto protoreflect.FileDescriptor

var file_narinfo_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6e, 0x61, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x22, 0xce, 0x02, 0x0a, 0x07, 0x4e, 0x61, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c,
	0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x48, 0x61, 0x73, 0x68, 0x12,
	0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x6e, 0x61, 0x72, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6e, 0x61, 0x72, 0x48, 0x61, 0x73, 0x68, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x61, 0x72, 0x5f, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6e, 0x61, 0x72, 0x53, 0x69,
	0x7a, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73,
	0x18, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x72, 0x69, 0x76, 0x65, 0x72, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x72, 0x69, 0x76, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x63, 0x61, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x63, 0x61, 0x42, 0x18, 0x5a, 0x16, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x64, 0x6e, 0x72, 0x2f, 0x73, 0x74, 0x79, 0x78, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_narinfo_proto_rawDescOnce sync.Once
	file_narinfo_proto_rawDescData = file_narinfo_proto_rawDesc
)

func file_narinfo_proto_rawDescGZIP() []byte {
	file_narinfo_proto_rawDescOnce.Do(func() {
		file_narinfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_narinfo_proto_rawDescData)
	})
	return file_narinfo_proto_rawDescData
}

var file_narinfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_narinfo_proto_goTypes = []any{
	(*NarInfo)(nil), // 0: pb.NarInfo
}
var file_narinfo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_narinfo_proto_init() }
func file_narinfo_proto_init() {
	if File_narinfo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_narinfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_narinfo_proto_goTypes,
		DependencyIndexes: file_narinfo_proto_depIdxs,
		MessageInfos:      file_narinfo_proto_msgTypes,
	}.Build()
	File_narinfo_proto = out.File
	file_narinfo_proto_rawDesc = nil
	file_narinfo_proto_goTypes = nil
	file_narinfo_proto_depIdxs = nil
}
